import React from "react";

export const SearchData = [
  {
    id: 1,
    name: "Burj Khalifa",
    rating: 4.7,
    poster: require("../Assets/img/Places/Bruj-Khalifa.jpg"),
    bigimage: require("../Assets/img/Places/Bruj-Khalifa2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "14,590",
    tourname: "Skip-The-Line Burj Khalifa Tour",
    perpersonprice: "14,590",
    familypack: "46,688",
    perpersonpricewithguide: "16,049",
    familypackwithguide: "49,022",
    timelimit: "Full day",
    genre: "Landmark",
    url: "/Burj-Khalifa.jsx",
  },
  {
    id: 2,
    name: "Burj Al Arab",
    rating: 4.7,
    poster: require("../Assets/img/Places/The-Burj-Al-Arab.jpg"),
    bigimage: require("../Assets/img/Places/The-Burj-Al-Arab2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "5,500",
    tourname: "Inside Burj Al Arab",
    perpersonprice: "5,500",
    familypack: "17,600",
    perpersonpricewithguide: "6,050",
    familypackwithguide: "18,480",
    timelimit: "2 Hours",
    genre: "Hotel",
    url: "/Burj-Al-Arab.jsx",
  },
  {
    id: 3,
    name: "Underwater Zoo",
    rating: 4.5,
    poster: require("../Assets/img/Places/Dubai-Aquarium-&-Underwater-Zoo.jpg"),
    bigimage: require("../Assets/img/Places/Dubai-Aquarium-&-Underwater-Zoo2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "3,347",
    tourname: "Dubai Aquarium & Underwater Zoo",
    perpersonprice: "3,347",
    familypack: "10,701",
    perpersonpricewithguide: "3,681",
    familypackwithguide: "11,236",
    timelimit: "1 - 6 Hours",
    genre: "Aquarium",
    url: "/Dubai-Aquarium-Underwater-Zoo.jsx",
  },
  {
    id: 4,
    name: "Dubai Miracle Garden",
    rating: 4.6,
    poster: require("../Assets/img/Places/Dubai-Miracle-Garden.jpg"),
    bigimage: require("../Assets/img/Places/Dubai-Miracle-Garden2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "5,891",
    tourname: "Miracle Round Trip",
    perpersonprice: "5,891",
    familypack: "18,851",
    perpersonpricewithguide: "6,480",
    familypackwithguide: "19,793",
    timelimit: "3 Hours",
    genre: "Garden",
    url: "/Dubai-Miracle-Garden.jsx",
  },
  {
    id: 5,
    name: "The Dubai Fountain",
    rating: 4.8,
    poster: require("../Assets/img/Places/The-Dubai-Fountain.jpg"),
    bigimage: require("../Assets/img/Places/The-Dubai-Fountain2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "6,228",
    tourname: "Show Lake Ride",
    perpersonprice: "6,228",
    familypack: "19,929",
    perpersonpricewithguide: "6,850",
    familypackwithguide: "20,925",
    timelimit: "30 Minutes",
    genre: "Fountain",
    url: "/The-Dubai-Fountain.jsx",
  },
  {
    id: 6,
    name: "Dubai Mall",
    rating: 4.7,
    poster: require("../Assets/img/Places/Dubai-Mall.jpg"),
    bigimage: require("../Assets/img/Places/Dubai-Mall2.jpeg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "Free !",
    tourname: "Let's Shop",
    perpersonprice: "Free !",
    familypack: "Free !",
    perpersonpricewithguide: "Not Needed",
    familypackwithguide: "Not Needed",
    timelimit: "Full day",
    genre: "Shopping Center",
    url: "/Dubai-Mall.jsx",
  },
  {
    id: 7,
    name: "Ski Dubai",
    rating: 4.5,
    poster: require("../Assets/img/Places/Ski-Dubai.jpg"),
    bigimage: require("../Assets/img/Places/Ski-Dubai2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "5,828",
    tourname: "Snow Classic",
    perpersonprice: "5,828",
    familypack: "23,312",
    perpersonpricewithguide: "6,410",
    familypackwithguide: "24,477",
    timelimit: "6 Hours",
    genre: "Ski resort",
    url: "/Ski-Dubai.jsx",
  },
  {
    id: 8,
    name: "Dubai Frame",
    rating: 4.6,
    poster: require("../Assets/img/Places/Dubai-Frame.jpg"),
    bigimage: require("../Assets/img/Places/Dubai-Frame2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "1,513",
    tourname: "Explore Frame",
    perpersonprice: "1,513",
    familypack: "4,841",
    perpersonpricewithguide: "1,664",
    familypackwithguide: "5,083",
    timelimit: "3 Hours",
    genre: "Monument",
    url: "/Dubai-Frame.jsx",
  },
  {
    id: 9,
    name: "Aquaventure Waterpark",
    rating: 4.5,
    poster: require("../Assets/img/Places/Aquaventure-Waterpark.jpg"),
    bigimage: require("../Assets/img/Places/Aquaventure-Waterpark2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "7,989",
    tourname: "Blue Aquaventure",
    perpersonprice: "7,989",
    familypack: "25,564",
    perpersonpricewithguide: "8,787",
    familypackwithguide: "26,842",
    timelimit: "7 - 8 Hours",
    genre: "Water Park",
    url: "/Aquaventure-Waterpark.jsx",
  },
  {
    id: 10,
    name: "Mall of the Emirates",
    rating: 4.5,
    poster: require("../Assets/img/Places/Mall-of-the-Emirates.jpg"),
    bigimage: require("../Assets/img/Places/Mall-of-the-Emirates2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "Free !",
    tourname: "Shopping Emirates",
    perpersonprice: "Free !",
    familypack: "Free !",
    perpersonpricewithguide: "Not Needed",
    familypackwithguide: "Not Needed",
    timelimit: "Full Day",
    genre: "Shopping Center",
    url: "/Mall-of-the-Emirates.jsx",
  },
  {
    id: 11,
    name: "Wild Wadi Waterpark Dubai",
    rating: 4.4,
    poster: require("../Assets/img/Places/Wild-Wadi-Waterpark-Dubai.jpg"),
    bigimage: require("../Assets/img/Places/Wild-Wadi-Waterpark-Dubai2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "6,181",
    tourname: "Enjoy Wild Wadi",
    perpersonprice: "6,181",
    familypack: "19,779",
    perpersonpricewithguide: "6,799",
    familypackwithguide: "20,767",
    timelimit: "9 Hours",
    genre: "Water Park",
    url: "/Wild-Wadi-Waterpark-Dubai.jsx",
  },
  {
    id: 12,
    name: "IMG Worlds of Adventure",
    rating: 4.4,
    poster: require("../Assets/img/Places/IMG-Worlds-of-Adventure.jpg"),
    bigimage: require("../Assets/img/Places/IMG-Worlds-of-Adventure2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "8,241",
    tourname: "Adventurous IMG World",
    perpersonprice: "8,241",
    familypack: "32,964",
    perpersonpricewithguide: "9,065",
    familypackwithguide: "34,612",
    timelimit: "1 Day",
    genre: "Theme Park",
    url: "/IMG-Worlds-of-Adventure.jsx",
  },
  {
    id: 13,
    name: "Jumeirah Mosque",
    rating: 4.6,
    poster: require("../Assets/img/Places/Jumeirah-Mosque.jpg"),
    bigimage: require("../Assets/img/Places/Jumeirah-Mosque2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "Free !",
    tourname: "Lovely Jumeirah",
    perpersonprice: "Free !",
    familypack: "Free !",
    perpersonpricewithguide: "Not Needed",
    familypackwithguide: "Not Needed",
    timelimit: "Full Day",
    genre: "Mosque",
    url: "/Jumeirah-Mosque.jsx",
  },
  {
    id: 14,
    name: "Dubai Dolphinarium",
    rating: 4.5,
    poster: require("../Assets/img/Places/Dubai-Dolphinarium.jpg"),
    bigimage: require("../Assets/img/Places/Dubai-Dolphinarium2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "2,119",
    tourname: "Dolphin Dolphinarium",
    perpersonprice: "2,119",
    familypack: "6,780",
    perpersonpricewithguide: "2,330",
    familypackwithguide: "7,119",
    timelimit: "9 Hours",
    genre: "Aquarium",
    url: "/Dubai-Dolphinarium.jsx",
  },
  {
    id: 15,
    name: "Al Fahidi Historical District",
    rating: 4.5,
    poster: require("../Assets/img/Places/Al-Fahidi-Historical.jpg"),
    bigimage: require("../Assets/img/Places/Al-Fahidi-Historical2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "2,539",
    tourname: "History Of Fahidi",
    perpersonprice: "2,539",
    familypack: "8,124",
    perpersonpricewithguide: "2,792",
    familypackwithguide: "8,530",
    timelimit: "Full Day",
    genre: "Landmark",
    url: "/Al-Fahidi-Historical.jsx",
  },
  {
    id: 16,
    name: "Museum of the Future",
    rating: 4.4,
    poster: require("../Assets/img/Places/Museum-of-the-Future.jpg"),
    bigimage: require("../Assets/img/Places/Museum-of-the-Future2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "3,427",
    tourname: "See The Future",
    perpersonprice: "3,427",
    familypack: "10,966",
    perpersonpricewithguide: "3,769",
    familypackwithguide: "11,514",
    timelimit: "2 Hours",
    genre: "Museum",
    url: "/Museum-of-the-Future.jsx",
  },
  {
    id: 17,
    name: "Dubai Garden Glow",
    rating: 4.5,
    poster: require("../Assets/img/Places/Dubai-Garden-Glow.jpg"),
    bigimage: require("../Assets/img/Places/Dubai-Garden-Glow2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "5,046",
    tourname: "Glowing Garden",
    perpersonprice: "5,046",
    familypack: "16,147",
    perpersonpricewithguide: "5,550",
    familypackwithguide: "16,954",
    timelimit: "3 Hours",
    genre: "Garden",
    url: "/Dubai-Garden-Glow.jsx",
  },
  {
    id: 18,
    name: "Legoland",
    rating: 4.4,
    poster: require("../Assets/img/Places/Legoland.jpg"),
    bigimage: require("../Assets/img/Places/Legoland2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "6,960",
    tourname: "Lego World",
    perpersonprice: "6,960",
    familypack: "22,272",
    perpersonpricewithguide: "7,656",
    familypackwithguide: "23,385",
    timelimit: "4 Hours",
    genre: "Theme Park",
    url: "/Legoland.jsx",
  },
  {
    id: 19,
    name: "Warner Bros. World",
    rating: 4.5,
    poster: require("../Assets/img/Places/Warner-Bros-World.jpg"),
    bigimage: require("../Assets/img/Places/Warner-Bros-World2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "7,148",
    tourname: "World Of W.B.",
    perpersonprice: "7,148",
    familypack: "22,873",
    perpersonpricewithguide: "7,505",
    familypackwithguide: "24,018",
    timelimit: "4 Hours",
    genre: "Theme Park",
    url: "/Warner-Bros-World.jsx",
  },
  {
    id: 20,
    name: "AYA Universe",
    rating: 4.4,
    poster: require("../Assets/img/Places/AYA-Universe.jpg"),
    bigimage: require("../Assets/img/Places/AYA-Universe2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "3,195",
    tourname: "Enjoyable Universe",
    perpersonprice: "3,195",
    familypack: "10,224",
    perpersonpricewithguide: "3,514",
    familypackwithguide: "10,735",
    timelimit: "10 Hours",
    genre: "Amusement Park",
    url: "/AYA-Universe.jsx",
  },
  {
    id: 21,
    name: "Al Seef",
    rating: 4.8,
    poster: require("../Assets/img/Places/Al-Seef.jpg"),
    bigimage: require("../Assets/img/Places/Al-Seef2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "8,410",
    tourname: "See Seef",
    perpersonprice: "8,410",
    familypack: "26,912",
    perpersonpricewithguide: "9,251",
    familypackwithguide: "28,257",
    timelimit: "3 Hours",
    genre: "Landmark",
    url: "/Al-Seef.jsx",
  },
  {
    id: 22,
    name: "Gold Souk",
    rating: 4.7,
    poster: require("../Assets/img/Places/Gold-Souk.jpg"),
    bigimage: require("../Assets/img/Places/Gold-Souk2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "Free !",
    tourname: "Golden Day",
    perpersonprice: "Free !",
    familypack: "Free !",
    perpersonpricewithguide: "Not Needed",
    familypackwithguide: "Not Needed",
    timelimit: "10 Hours",
    genre: "Market",
    url: "/Gold-Souk.jsx",
  },
  {
    id: 23,
    name: "Ferrari World",
    rating: 4.8,
    poster: require("../Assets/img/Places/Ferrari-World.jpg"),
    bigimage: require("../Assets/img/Places/Ferrari-World2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "7,949",
    tourname: "Ride The Ferrari",
    perpersonprice: "7,949",
    familypack: "25,436",
    perpersonpricewithguide: "8,743",
    familypackwithguide: "26,707",
    timelimit: "5 Hours",
    genre: "Theme Park",
    url: "/Ferrari-World.jsx",
  },
  {
    id: 24,
    name: "Atlantis, The Palm",
    rating: 4.8,
    poster: require("../Assets/img/Places/Atlantis-The-Palm.jpg"),
    bigimage: require("../Assets/img/Places/Atlantis-The-Palm2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "24,052",
    tourname: "Beautiful Atlantis",
    perpersonprice: "24,052",
    familypack: "76,966",
    perpersonpricewithguide: "26,457",
    familypackwithguide: "80,814",
    timelimit: "4 Hours",
    genre: "Hotel",
    url: "/Atlantis-The-Palm.jsx",
  },
  {
    id: 25,
    name: "Abu Dhabi Mosque",
    rating: 4.6,
    poster: require("../Assets/img/Places/Abu-Dhabi-Mosque.jpg"),
    bigimage: require("../Assets/img/Places/Abu-Dhabi-Mosque2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "Free !",
    tourname: "Abu Dhabi Mosque",
    perpersonprice: "Free !",
    familypack: "Free !",
    perpersonpricewithguide: "Not Neede",
    familypackwithguide: "Not Needed",
    timelimit: "9 Hours",
    genre: "Mosque",
    url: "/Abu-Dhabi-Mosque.jsx",
  },
  {
    id: 26,
    name: "Dubai Water Canal",
    rating: 4.8,
    poster: require("../Assets/img/Places/Dubai-Water-Canal.jpg"),
    bigimage: require("../Assets/img/Places/Dubai-Water-Canal2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "4,707",
    tourname: "Canal Cruise",
    perpersonprice: "4,707",
    familypack: "15,062",
    perpersonpricewithguide: "5,177",
    familypackwithguide: "15,815",
    timelimit: "2 Hours 30 minutes",
    genre: "Landmark",
    url: "/Dubai-Water-Canal.jsx",
  },
  {
    id: 27,
    name: "Bluewaters Island",
    rating: 4.6,
    poster: require("../Assets/img/Places/Bluewaters-Island.jpg"),
    bigimage: require("../Assets/img/Places/Bluewaters-Island2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "8,957",
    tourname: "Blue Land",
    perpersonprice: "8,957",
    familypack: "28,662",
    perpersonpricewithguide: "9,852",
    familypackwithguide: "30,095",
    timelimit: "7 Hours",
    genre: "Island",
    url: "/Bluewaters-Island.jsx",
  },
  {
    id: 28,
    name: "Jumeirah Beach Residence",
    rating: 4.5,
    poster: require("../Assets/img/Places/Jumeirah-Beach-Residence.jpg"),
    bigimage: require("../Assets/img/Places/Jumeirah-Beach-Residence2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "8,014",
    tourname: "Wondering Jumeirah Beach",
    perpersonprice: "8,014",
    familypack: "25,644",
    perpersonpricewithguide: "8,815",
    familypackwithguide: "26,926",
    timelimit: "1 Hour",
    genre: "Beach",
    url: "/Jumeirah-Beach-Residence.jsx",
  },
  {
    id: 29,
    name: "Sky Views Observatory",
    rating: 4.7,
    poster: require("../Assets/img/Places/Sky-Views-Observatory.jpg"),
    bigimage: require("../Assets/img/Places/Sky-Views-Observatory2.jpeg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "2,510",
    tourname: "Gorgeous Sky",
    perpersonprice: "2,510",
    familypack: "8,032",
    perpersonpricewithguide: "2,761",
    familypackwithguide: "8,4336",
    timelimit: "1 Hour",
    genre: "Observatory",
    url: "/Sky-Views-Observatory.jsx",
  },
  {
    id: 30,
    name: "Al Rahim Mosque",
    rating: 4.4,
    poster: require("../Assets/img/Places/Al-Rahim-Mosque.jpg"),
    bigimage: require("../Assets/img/Places/Al-Rahim-Mosque2.jpg"),
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Libero et, fugit voluptatum aliquid.",
    avgprice: "Free !",
    tourname: "Al Rahim Mosque",
    perpersonprice: "Free !",
    familypack: "Free !",
    perpersonpricewithguide: "Not Needed",
    familypackwithguide: "Not Needed",
    timelimit: "9 Hours",
    genre: "Mosque",
    url: "/Al-Rahim-Mosque.jsx",
  },
];